### PR TITLE
add gridgmgmt folder and content

### PR DESCRIPTION
**Pull request by sbuser-git**
Resolved #XXXX.

### CODE REVIEW

**Comment by ddb4github** [comment]
* Some php file missed `ident` line `$Id: $`
* Some index.php is ionCube Encoded files, should be plain-text file
* Function `grid_get_host_records` is not PHP 8 compatible. the latest param should be changed to `$rows = 30`
* Function `grid_view_get_dstat_records` has same issue

**Review by TheWitness — CHANGES_REQUESTED** [review]
@sbuser-git, if you can replace the index.php with unencoded versions, that would help this one along.  I saw three of them.  You can simply pull the version from the plugins folder.  They are all pretty much redirects back up to the cacti root anyway.

**Comment by TheWitness** [comment]
Thanks for the feedback @ddb4github.

**Comment by sbuser-git** [comment]
@TheWitness please check index.php now 👍

**Comment by TheWitness** [comment]
Yea, perfect.  The other issues deal with adding defaults to some optional function arguments.

**Comment by sbuser-git** [comment]
closing out to create separate requests

**Pull request closed without merging**
