### PR TITLE
poller_options updates

### PR DESCRIPTION
**Pull request by sbuser-git**
Resolved #XXXX.

### CODE REVIEW

**Comment by TheWitness** [comment]
@ddb4github, any updates on this?

**Comment by TheWitness** [comment]
@ddb4github, second request...

**Comment by ddb4github** [comment]
> @ddb4github, second request...

At least, gridgmgmt should be a single PR.

**Comment by ddb4github** [comment]
After discussed with @TheWitness.
Could  PR author split current PR to  three PR:
* one for new plugin `gridgmgmt`
* one for three files of `grid` plugin
* one for poller_options.php of `license` plugin

So, I'll close this PR now.
Thanks

**Pull request closed without merging**
